from os import getenv
from dotenv import load_dotenv

load_dotenv()

que = {}
admins = {}
SESSION_NAME = getenv("SESSION_NAME", "session")
BOT_TOKEN = getenv("BOT_TOKEN")
BOT_NAME = getenv("BOT_NAME")
BOT_USERNAME = getenv("BOT_USERNAME")
ASSID = int(getenv("ASSID"))
ASSNAME = getenv("ASSNAME")
ASSUSERNAME = getenv("ASSUSERNAME")
BOT_ID = int(getenv("BOT_ID"))
UPSTREAM_REPO = getenv("UPSTREAM_REPO")
UPSTREAM_BRANCH = getenv("UPSTREAM_BRANCH")
HEROKU_API_KEY = getenv("HEROKU_API_KEY")
HEROKU_APP_NAME = getenv("HEROKU_APP_NAME")
MONGO_DB_URI = getenv("MONGO_DB_URI")
API_ID = int(getenv("API_ID"))
API_HASH = getenv("API_HASH")
OWNER_ID = int(getenv("OWNER_ID", "5448900586"))
UPDATE = getenv("UPDATE", "COMRADE_ROBOTZ")
SUPPORT = getenv("SUPPORT", "COMRADE_BOTZ")
DURATION_LIMIT = int(getenv("DURATION_LIMIT", "9999"))
CMD_MUSIC = list(getenv("CMD_MUSIC", "/ !").split())
BG_IMG = getenv("BG_IMG", "https://telegra.ph/file/fdbdd8ae2e24f8f927f7d.jpg")
SUDO_USERS = list(map(int, getenv("SUDO_USERS", "5448900586").split()))
START_PIC = getenv("START_PIC", "https://telegra.ph/file/3aa46509507762ee6d42f.jpg")
OWNER_USERNAME = getenv("OWNER_USERNAME")
IMG_1 = getenv("IMG_1", "https://telegra.ph/file/f9238537c1e39baf8e501.jpg")
IMG_2 = getenv("IMG_2", "https://telegra.ph/file/6c64c2bc7a7b9bd6abe75.jpg")
IMG_3 = getenv("IMG_3", "https://telegra.ph/file/28069e0d7be4eae3b1320.jpg")
IMG_4 = getenv("IMG_4", "https://telegra.ph/file/ca24b86caee0922a1df9f.jpg")
